### ISSUE TITLE
mpris-service not found

### ISSUE THREAD

**Issue by eddy85br** [baptistedonaux/deezer-desktop-linux#1]
Error: Cannot find module 'mpris-service'

`npm install` worked with a few warnings, but `npm start` throw this error.

```
npm start

> @ start /home/[...]/deezer-desktop-linux-master
> electron app/main.js

Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.36.12/docs

Error: Cannot find module 'mpris-service'

```
`npm install mpris-service` doesn't work. Any idea why?

**Comment by eddy85br** [comment]
I resolved part of the problem with:
1] `sudo apt-get install libdbus-1-dev`
2] `npm install dbus`
3] `npm install mpris-service`

But now, the error is this:
```
npm start

> @ start /home/[...]/deezer-desktop-linux-master
> electron app/main.js

App threw an error when running [Error: Module version mismatch. Expected 47, got 46.]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/[...]deezer-desktop-linux-master/node_modules/dbus/lib/dbus.js:3:13)
    at Module._compile (module.js:425:26)
```

**Comment by baptistedonaux** [comment]
Thanks for your feedback.

To build project you can follow these steps : 
- ```npm install```
- ```npm run pepper```
- ```npm run build```
- ```npm run dist```

In re-executing these steps, I have an error with the last step. Could you reproduce ?

**Comment by baptistedonaux** [comment]
But the project execution with ```npm start``` works.

**Comment by baptistedonaux** [comment]
A short README has been added.

Thank you for your report. You can open others issues to contribute or send me PRs ;-)
