### ISSUE TITLE
Which is the status?

### ISSUE THREAD

**Issue by williamlopes-dev** [baptistedonaux/deezer-desktop-linux#2]
Hi,

I'm a developer too, and I would like know if the project is working. Maybe I can help you to finish it.

Thanks.

**Comment by baptistedonaux** [comment]
Hi @williamlopes-dev 

You can contribtued on this project. Currently, its activity is low because I'm blocking with the final compilation. (Fail with a Node API version which mismatch).

I will be happy to help you a propose an integration of Deezer for Linux.

**Comment by baptistedonaux** [comment]
Current error
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/baptiste/Project/deezer-app/app/node_modules/dbus/lib/dbus.js:3:13)
```

Node: ```v6.9.5```

**Comment by baptistedonaux** [comment]
I success to build and run the project. You can follow steps and proposes documentations improvements or anythings :-)

**Comment by baptistedonaux** [comment]
I published the first released for [AMD64 and Debian packager](https://github.com/baptistedonaux/deezer-desktop-linux/releases/tag/v0.0.1).

It's a basic package which must improved. I wait contributions 😃

**Comment by williamlopes-dev** [comment]
Hi @baptistedonaux 

I'm glad to help the community. But I can't work this week, maybe in the next. OK?

I already forked your project, in the next week we work together.

Hugs.
