### ISSUE TITLE
Javascript Error: Version Mismatch

### ISSUE THREAD

**Issue by jpts** [baptistedonaux/deezer-desktop-linux#4]
When first trying to install this I came across the following error (using `npm install && npm start`)

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jpts/deezer-desktop-linux/node_modules/mpris-service/node_modules/dbus/lib/dbus.js:3:13)
```
I was able to fix this using the following command
`npm rebuild --runtime=electron --target=1.4.13 --disturl=https://atom.io/download/electron --arch=x64`

Perhaps there a way of including this in a post-install script?

([source](https://github.com/electron-userland/electron-builder/issues/453#issuecomment-243341716),[source](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-easy-way))

**Comment by mesmerx** [comment]
npm install --save electron@1.5   

solve this

**Comment by baptistedonaux** [comment]
This project is no longer maintained. You can use [MellowPlayer](https://colinduquesnoy.github.io/MellowPlayer/).
