### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ZeroDot1** [baptistedonaux/deezer-desktop-linux#6]
`'/opt/deezer-desktop-linux-linux-x64/deezer-desktop-linux'
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/deezer-desktop-linux-linux-x64/resources/app/node_modules/dbus/lib/dbus.js:3:13)
`

**Comment by xoac** [comment]
The same +1

**Comment by ZeroDot1** [comment]
I use a good software https://github.com/ColinDuquesnoy/MellowPlayer

**Comment by baptistedonaux** [comment]
@ZeroDot1 Thanks for your feedback about your current software. It seems better than Deezer Dektop for Linux and I close this project right now and invite everybody to use it.
